### ISSUE TITLE
Document the 'reinstall' action

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/layer-filebeat#58]
When I upgraded the filebeat charm to the latest version (18), all the units were in 'blocked' state with "Install filebeat-5.6.10 with the 'reinstall' action.".  I tried running this, but the status isn't changing:

```
juju run --application filebeat 'sudo DEBIAN_FRONTEND=noninteractive apt-get install --reinstall -y -o Dpkg::Options::="--force-confdef" filebeat'
```

In the unit log, even after running the reinstall, I see:
```
2018-07-11 05:51:41 INFO juju-log status-set: blocked: Install filebeat-5.6.10 with the 'reinstall' action.
```

**Comment by xtrusia** [comment]
juju run --unit filebeat/x 'actions/reinstall'

can solve this problem. but I don't know why this issue happened.

**Comment by xtrusia** [comment]
I'm not sure I can share plain log of the customer's,

so I paste link canonical pastebin

https://pastebin.canonical.com/p/CxdTGb8xb4/

**Comment by kwmonroe** [comment]
@xavpaice @xtrusia, this is an issue with the documentation.  When you see this status:
```
Install filebeat-5.6.10 with the 'reinstall' action.
```
We expect operators to run this:
```
juju run-action --wait filebeat/0 reinstall
```

@xavpaice, you had a excellent idea of running `apt --reinstall`, but the intention was for operators to run the literal `reinstall` action on each unit.  In fact, you probably *did* upgrade filebeat to the new version with `apt --reinstall`, but the charm doesn't know that because the `filebeat.reinstall` flag is not cleared when running `apt` directly on the system.

Support for `reinstall` came in with https://github.com/juju-solutions/layer-beats-base/pull/27.  Unfortunately, i did not include instructions in the beats readmes for how to handle the new status message.  Sorry about that!

I'll keep this issue open and note it as a doc problem.  If your filebeat units are still `blocked`, please run the `reinstall` action as noted above and let me know if you have any problems.  I'll get the docs updated asap.

**Comment by kwmonroe** [comment]
FYI, this has been released in charm rev >= 19:

https://jujucharms.com/filebeat/19

**Comment by afreiberger** [comment]
Why should this be something an operator must trigger?  Charms should handle underlying apt upgrades whether done inside or outside of the charm hooks.

Using an action to fix a charm bug seems like a poor waste of operator time.  I just had to run 200 actions in a large cloud using this filebeat charm.  Instead of the charm requiring the user to call the action, the charm's update-status should call the action code itself.
